baseURL = 'http://recipes.timharding.co/'
languageCode = 'en-us'
title = 'Recipes'
theme = "recipes_theme"

[deployment]
[[deployment.targets]]
name = "aws_s3_deployment"
URL = "s3://recipes.timharding.co?region=us-west-2"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=6000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true